# Generated by Django 2.1.5 on 2019-02-17 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_text', models.CharField(max_length=600)),
                ('time_stamp', models.IntegerField(default=0)),
                ('sender', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'get_latest_by': 'time_stamp',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=60, unique=True)),
                ('room_id', models.CharField(max_length=80, unique=True)),
                ('joined', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.Room'),
        ),
    ]
