# Generated by Django 2.1.5 on 2019-02-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_text', models.CharField(max_length=600)),
                ('time_stamp', models.IntegerField(default=0)),
                ('sender', models.CharField(max_length=100)),
            ],
            options={
                'get_latest_by': 'time_stamp',
            },
        ),
    ]
