# Generated by Django 2.1.7 on 2019-02-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='background_color',
            field=models.CharField(default='blue', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='room',
            name='joined',
            field=models.BooleanField(default=False),
        ),
    ]
